// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"
)

const countFilesForAsset = `-- name: CountFilesForAsset :one
SELECT count(*) FROM files WHERE asset_id = ?
`

func (q *Queries) CountFilesForAsset(ctx context.Context, assetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilesForAsset, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = ?
`

func (q *Queries) DeleteAsset(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAsset, id)
	return err
}

const deleteDerivativesForAsset = `-- name: DeleteDerivativesForAsset :exec
DELETE FROM derivatives WHERE asset_id = ?
`

func (q *Queries) DeleteDerivativesForAsset(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteDerivativesForAsset, assetID)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE media_path = ?
`

func (q *Queries) DeleteFile(ctx context.Context, mediaPath string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, mediaPath)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, alias, dir, base_name, kind, display_path, needs_develop, captured_at, created_at, updated_at
FROM assets WHERE id = ?
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Dir,
		&i.BaseName,
		&i.Kind,
		&i.DisplayPath,
		&i.NeedsDevelop,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDerivative = `-- name: GetDerivative :one
SELECT asset_id, kind, params, path, mime, src_hash, created_at
FROM derivatives WHERE asset_id = ? AND kind = ? AND params = ?
`

type GetDerivativeParams struct {
	AssetID string `json:"asset_id"`
	Kind    string `json:"kind"`
	Params  string `json:"params"`
}

func (q *Queries) GetDerivative(ctx context.Context, arg GetDerivativeParams) (Derivative, error) {
	row := q.db.QueryRowContext(ctx, getDerivative, arg.AssetID, arg.Kind, arg.Params)
	var i Derivative
	err := row.Scan(
		&i.AssetID,
		&i.Kind,
		&i.Params,
		&i.Path,
		&i.Mime,
		&i.SrcHash,
		&i.CreatedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT media_path, asset_id, kind, size, mod_time, hash
FROM files WHERE media_path = ?
`

func (q *Queries) GetFile(ctx context.Context, mediaPath string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, mediaPath)
	var i File
	err := row.Scan(
		&i.MediaPath,
		&i.AssetID,
		&i.Kind,
		&i.Size,
		&i.ModTime,
		&i.Hash,
	)
	return i, err
}

const listAllAssets = `-- name: ListAllAssets :many
SELECT id, alias, dir, base_name, kind, display_path, needs_develop, captured_at, created_at, updated_at
FROM assets WHERE alias = ?
ORDER BY dir, base_name
`

// All assets in a library (for warm-cache / bulk passes), folder order.
func (q *Queries) ListAllAssets(ctx context.Context, alias string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssets, alias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.Dir,
			&i.BaseName,
			&i.Kind,
			&i.DisplayPath,
			&i.NeedsDevelop,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllFiles = `-- name: ListAllFiles :many
SELECT media_path, asset_id, kind, size, mod_time, hash
FROM files WHERE asset_id IN (SELECT id FROM assets WHERE alias = ?)
ORDER BY media_path
`

// Full snapshot of catalogued files for a library, used by the reconcile scan
// to diff against the on-disk walk on (path, mtime, size).
func (q *Queries) ListAllFiles(ctx context.Context, alias string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listAllFiles, alias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.MediaPath,
			&i.AssetID,
			&i.Kind,
			&i.Size,
			&i.ModTime,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByDir = `-- name: ListAssetsByDir :many
SELECT id, alias, dir, base_name, kind, display_path, needs_develop, captured_at, created_at, updated_at
FROM assets
WHERE alias = ? AND dir = ? AND base_name > ?
ORDER BY base_name
LIMIT ?
`

type ListAssetsByDirParams struct {
	Alias    string `json:"alias"`
	Dir      string `json:"dir"`
	BaseName string `json:"base_name"`
	Limit    int64  `json:"limit"`
}

// Keyset (cursor) pagination by base_name within a folder. The cursor is the
// last base_name seen; pass "" to start. Fetches limit+1 so the caller can
// detect a next page.
func (q *Queries) ListAssetsByDir(ctx context.Context, arg ListAssetsByDirParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByDir,
		arg.Alias,
		arg.Dir,
		arg.BaseName,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.Dir,
			&i.BaseName,
			&i.Kind,
			&i.DisplayPath,
			&i.NeedsDevelop,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDerivativesForAsset = `-- name: ListDerivativesForAsset :many
SELECT asset_id, kind, params, path, mime, src_hash, created_at
FROM derivatives WHERE asset_id = ?
`

func (q *Queries) ListDerivativesForAsset(ctx context.Context, assetID string) ([]Derivative, error) {
	rows, err := q.db.QueryContext(ctx, listDerivativesForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Derivative{}
	for rows.Next() {
		var i Derivative
		if err := rows.Scan(
			&i.AssetID,
			&i.Kind,
			&i.Params,
			&i.Path,
			&i.Mime,
			&i.SrcHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirsForLibrary = `-- name: ListDirsForLibrary :many
SELECT DISTINCT dir FROM assets WHERE alias = ? AND dir <> '' ORDER BY dir
`

// All distinct (non-empty) directories holding assets in a library. The browse
// handler derives immediate child folders of a given dir from this in Go (the
// substring arithmetic SQLite would need is brittle through sqlc's parser).
func (q *Queries) ListDirsForLibrary(ctx context.Context, alias string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDirsForLibrary, alias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var dir string
		if err := rows.Scan(&dir); err != nil {
			return nil, err
		}
		items = append(items, dir)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesForAsset = `-- name: ListFilesForAsset :many
SELECT media_path, asset_id, kind, size, mod_time, hash
FROM files WHERE asset_id = ?
ORDER BY media_path
`

func (q *Queries) ListFilesForAsset(ctx context.Context, assetID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.MediaPath,
			&i.AssetID,
			&i.Kind,
			&i.Size,
			&i.ModTime,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAssetCapturedAt = `-- name: SetAssetCapturedAt :exec
UPDATE assets SET captured_at = ?, updated_at = datetime('now') WHERE id = ?
`

type SetAssetCapturedAtParams struct {
	CapturedAt *string `json:"captured_at"`
	ID         string  `json:"id"`
}

func (q *Queries) SetAssetCapturedAt(ctx context.Context, arg SetAssetCapturedAtParams) error {
	_, err := q.db.ExecContext(ctx, setAssetCapturedAt, arg.CapturedAt, arg.ID)
	return err
}

const upsertAsset = `-- name: UpsertAsset :exec

INSERT INTO assets (id, alias, dir, base_name, kind, display_path, needs_develop, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(id) DO UPDATE SET
    alias         = excluded.alias,
    dir           = excluded.dir,
    base_name     = excluded.base_name,
    kind          = excluded.kind,
    display_path  = excluded.display_path,
    needs_develop = excluded.needs_develop,
    updated_at    = excluded.updated_at
`

type UpsertAssetParams struct {
	ID           string `json:"id"`
	Alias        string `json:"alias"`
	Dir          string `json:"dir"`
	BaseName     string `json:"base_name"`
	Kind         string `json:"kind"`
	DisplayPath  string `json:"display_path"`
	NeedsDevelop int64  `json:"needs_develop"`
}

// media-pipeline catalog queries (sqlc). Domain: assets / files / derivatives.
// See docs/specs/_contracts.md sec.3 for the type shapes and sec.6 for conventions.
func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) error {
	_, err := q.db.ExecContext(ctx, upsertAsset,
		arg.ID,
		arg.Alias,
		arg.Dir,
		arg.BaseName,
		arg.Kind,
		arg.DisplayPath,
		arg.NeedsDevelop,
	)
	return err
}

const upsertDerivative = `-- name: UpsertDerivative :exec
INSERT INTO derivatives (asset_id, kind, params, path, mime, src_hash)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(asset_id, kind, params) DO UPDATE SET
    path     = excluded.path,
    mime     = excluded.mime,
    src_hash = excluded.src_hash,
    created_at = datetime('now')
`

type UpsertDerivativeParams struct {
	AssetID string `json:"asset_id"`
	Kind    string `json:"kind"`
	Params  string `json:"params"`
	Path    string `json:"path"`
	Mime    string `json:"mime"`
	SrcHash string `json:"src_hash"`
}

func (q *Queries) UpsertDerivative(ctx context.Context, arg UpsertDerivativeParams) error {
	_, err := q.db.ExecContext(ctx, upsertDerivative,
		arg.AssetID,
		arg.Kind,
		arg.Params,
		arg.Path,
		arg.Mime,
		arg.SrcHash,
	)
	return err
}

const upsertFile = `-- name: UpsertFile :exec
INSERT INTO files (media_path, asset_id, kind, size, mod_time, hash)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(media_path) DO UPDATE SET
    asset_id = excluded.asset_id,
    kind     = excluded.kind,
    size     = excluded.size,
    mod_time = excluded.mod_time,
    hash     = excluded.hash
`

type UpsertFileParams struct {
	MediaPath string `json:"media_path"`
	AssetID   string `json:"asset_id"`
	Kind      string `json:"kind"`
	Size      int64  `json:"size"`
	ModTime   string `json:"mod_time"`
	Hash      string `json:"hash"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertFile,
		arg.MediaPath,
		arg.AssetID,
		arg.Kind,
		arg.Size,
		arg.ModTime,
		arg.Hash,
	)
	return err
}
