// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'claimed',
    lease_until = datetime('now', ?),
    attempts = attempts + 1,
    updated_at = datetime('now')
WHERE id = ?
  AND available_at <= datetime('now')
  AND (
        status = 'pending'
     OR (status = 'claimed' AND (lease_until IS NULL OR lease_until <= datetime('now')))
  )
RETURNING id, kind, asset_id, media_path, params, status, attempts, max_attempts, available_at, lease_until, last_error, result_data, created_at, updated_at
`

type ClaimJobParams struct {
	Datetime interface{} `json:"datetime"`
	ID       string      `json:"id"`
}

// ClaimJob marks one selected row claimed, sets its lease and bumps attempts.
// It is guarded by the same predicate as SelectClaimable so a row that changed
// between select and update (impossible under the single writer, but correct
// regardless) is not double-claimed.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, arg.Datetime, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AssetID,
		&i.MediaPath,
		&i.Params,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE jobs
SET status = 'completed',
    lease_until = NULL,
    result_data = ?,
    last_error = NULL,
    updated_at = datetime('now')
WHERE id = ? AND status = 'claimed'
`

type CompleteJobParams struct {
	ResultData *string `json:"result_data"`
	ID         string  `json:"id"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeJob, arg.ResultData, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countJobsByStatus = `-- name: CountJobsByStatus :one
SELECT COUNT(*) FROM jobs WHERE status = ?
`

func (q *Queries) CountJobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO jobs (id, kind, asset_id, media_path, params, max_attempts, status, available_at)
VALUES (?, ?, ?, ?, ?, ?, 'pending', datetime('now'))
RETURNING id, kind, asset_id, media_path, params, status, attempts, max_attempts, available_at, lease_until, last_error, result_data, created_at, updated_at
`

type EnqueueJobParams struct {
	ID          string `json:"id"`
	Kind        string `json:"kind"`
	AssetID     string `json:"asset_id"`
	MediaPath   string `json:"media_path"`
	Params      string `json:"params"`
	MaxAttempts int64  `json:"max_attempts"`
}

// jobs-worker queries over the durable job queue (see migration 0300_jobs.sql).
// The claim path is split into a SELECT of claimable ids and a per-id UPDATE so
// it can run inside one serialized write transaction; with the single-writer
// SQLite connection this guarantees no two claims ever take the same row.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob,
		arg.ID,
		arg.Kind,
		arg.AssetID,
		arg.MediaPath,
		arg.Params,
		arg.MaxAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AssetID,
		&i.MediaPath,
		&i.Params,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :execrows
UPDATE jobs
SET status = 'failed',
    lease_until = NULL,
    last_error = ?,
    updated_at = datetime('now')
WHERE id = ? AND status = 'claimed'
`

type FailJobParams struct {
	LastError *string `json:"last_error"`
	ID        string  `json:"id"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failJob, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getJob = `-- name: GetJob :one
SELECT id, kind, asset_id, media_path, params, status, attempts, max_attempts, available_at, lease_until, last_error, result_data, created_at, updated_at FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AssetID,
		&i.MediaPath,
		&i.Params,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.ResultData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
SET status = 'pending',
    lease_until = NULL,
    last_error = ?,
    available_at = datetime('now', ?),
    updated_at = datetime('now')
WHERE id = ? AND status = 'claimed'
`

type RetryJobParams struct {
	LastError *string     `json:"last_error"`
	Datetime  interface{} `json:"datetime"`
	ID        string      `json:"id"`
}

// RetryJob reschedules a failed-but-retryable job: back to pending with a
// future availability (caller computes the backoff offset string).
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryJob, arg.LastError, arg.Datetime, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectClaimable = `-- name: SelectClaimable :many
SELECT id FROM jobs
WHERE available_at <= datetime('now')
  AND (
        status = 'pending'
     OR (status = 'claimed' AND (lease_until IS NULL OR lease_until <= datetime('now')))
  )
ORDER BY available_at ASC, created_at ASC
LIMIT ?
`

// SelectClaimable returns up to ? ids of jobs that are claimable right now: a
// pending job whose availability has arrived, or a claimed job whose lease has
// lapsed (worker died/stalled). Oldest-available first for FIFO fairness.
func (q *Queries) SelectClaimable(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, selectClaimable, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
