// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type AppMetum struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type Asset struct {
	ID           string  `json:"id"`
	Alias        string  `json:"alias"`
	Dir          string  `json:"dir"`
	BaseName     string  `json:"base_name"`
	Kind         string  `json:"kind"`
	DisplayPath  string  `json:"display_path"`
	NeedsDevelop int64   `json:"needs_develop"`
	CapturedAt   *string `json:"captured_at"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

type AssetsFt struct {
	AssetID string `json:"asset_id"`
	Name    string `json:"name"`
	Camera  string `json:"camera"`
	Lens    string `json:"lens"`
	Labels  string `json:"labels"`
	Caption string `json:"caption"`
	Ocr     string `json:"ocr"`
	Persons string `json:"persons"`
}

type Derivative struct {
	AssetID   string `json:"asset_id"`
	Kind      string `json:"kind"`
	Params    string `json:"params"`
	Path      string `json:"path"`
	Mime      string `json:"mime"`
	SrcHash   string `json:"src_hash"`
	CreatedAt string `json:"created_at"`
}

type Embedding struct {
	AssetID   string `json:"asset_id"`
	Dim       int64  `json:"dim"`
	Vec       []byte `json:"vec"`
	UpdatedAt string `json:"updated_at"`
}

type EnrichmentRun struct {
	AssetID     string `json:"asset_id"`
	Kind        string `json:"kind"`
	ContentHash string `json:"content_hash"`
	RanAt       string `json:"ran_at"`
}

type Face struct {
	ID          string  `json:"id"`
	AssetID     string  `json:"asset_id"`
	PersonID    *string `json:"person_id"`
	BboxX       float64 `json:"bbox_x"`
	BboxY       float64 `json:"bbox_y"`
	BboxW       float64 `json:"bbox_w"`
	BboxH       float64 `json:"bbox_h"`
	Confidence  float64 `json:"confidence"`
	ExtRef      string  `json:"ext_ref"`
	ContentHash string  `json:"content_hash"`
	CreatedAt   string  `json:"created_at"`
}

type File struct {
	MediaPath string `json:"media_path"`
	AssetID   string `json:"asset_id"`
	Kind      string `json:"kind"`
	Size      int64  `json:"size"`
	ModTime   string `json:"mod_time"`
	Hash      string `json:"hash"`
}

type Job struct {
	ID          string  `json:"id"`
	Kind        string  `json:"kind"`
	AssetID     string  `json:"asset_id"`
	MediaPath   string  `json:"media_path"`
	Params      string  `json:"params"`
	Status      string  `json:"status"`
	Attempts    int64   `json:"attempts"`
	MaxAttempts int64   `json:"max_attempts"`
	AvailableAt string  `json:"available_at"`
	LeaseUntil  *string `json:"lease_until"`
	LastError   *string `json:"last_error"`
	ResultData  *string `json:"result_data"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type Metadata struct {
	AssetID     string   `json:"asset_id"`
	CapturedAt  *string  `json:"captured_at"`
	CameraMake  string   `json:"camera_make"`
	CameraModel string   `json:"camera_model"`
	Lens        string   `json:"lens"`
	Width       int64    `json:"width"`
	Height      int64    `json:"height"`
	Orientation int64    `json:"orientation"`
	DurationMs  int64    `json:"duration_ms"`
	Codec       string   `json:"codec"`
	GpsLat      *float64 `json:"gps_lat"`
	GpsLng      *float64 `json:"gps_lng"`
	Source      string   `json:"source"`
	IndexedAt   string   `json:"indexed_at"`
}

type Person struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	CoverFaceID   string `json:"cover_face_id"`
	ExtCollection string `json:"ext_collection"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}
