// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package store

import (
	"context"
)

const assignFacePerson = `-- name: AssignFacePerson :exec
UPDATE faces SET person_id = ? WHERE id = ?
`

type AssignFacePersonParams struct {
	PersonID *string `json:"person_id"`
	ID       string  `json:"id"`
}

func (q *Queries) AssignFacePerson(ctx context.Context, arg AssignFacePersonParams) error {
	_, err := q.db.ExecContext(ctx, assignFacePerson, arg.PersonID, arg.ID)
	return err
}

const countFacesForPerson = `-- name: CountFacesForPerson :one
SELECT COUNT(*) FROM faces WHERE person_id = ?
`

func (q *Queries) CountFacesForPerson(ctx context.Context, personID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFacesForPerson, personID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFacesForAsset = `-- name: DeleteFacesForAsset :exec
DELETE FROM faces WHERE asset_id = ?
`

func (q *Queries) DeleteFacesForAsset(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteFacesForAsset, assetID)
	return err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM persons WHERE id = ?
`

func (q *Queries) DeletePerson(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePerson, id)
	return err
}

const getFace = `-- name: GetFace :one
SELECT id, asset_id, person_id, bbox_x, bbox_y, bbox_w, bbox_h,
       confidence, ext_ref, content_hash
FROM faces WHERE id = ?
`

type GetFaceRow struct {
	ID          string  `json:"id"`
	AssetID     string  `json:"asset_id"`
	PersonID    *string `json:"person_id"`
	BboxX       float64 `json:"bbox_x"`
	BboxY       float64 `json:"bbox_y"`
	BboxW       float64 `json:"bbox_w"`
	BboxH       float64 `json:"bbox_h"`
	Confidence  float64 `json:"confidence"`
	ExtRef      string  `json:"ext_ref"`
	ContentHash string  `json:"content_hash"`
}

func (q *Queries) GetFace(ctx context.Context, id string) (GetFaceRow, error) {
	row := q.db.QueryRowContext(ctx, getFace, id)
	var i GetFaceRow
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.PersonID,
		&i.BboxX,
		&i.BboxY,
		&i.BboxW,
		&i.BboxH,
		&i.Confidence,
		&i.ExtRef,
		&i.ContentHash,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, name, cover_face_id, ext_collection FROM persons WHERE id = ?
`

type GetPersonRow struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	CoverFaceID   string `json:"cover_face_id"`
	ExtCollection string `json:"ext_collection"`
}

func (q *Queries) GetPerson(ctx context.Context, id string) (GetPersonRow, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i GetPersonRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoverFaceID,
		&i.ExtCollection,
	)
	return i, err
}

const hasEnrichmentRun = `-- name: HasEnrichmentRun :one
SELECT EXISTS (
    SELECT 1 FROM enrichment_runs
    WHERE asset_id = ? AND kind = ? AND content_hash = ?
) AS present
`

type HasEnrichmentRunParams struct {
	AssetID     string `json:"asset_id"`
	Kind        string `json:"kind"`
	ContentHash string `json:"content_hash"`
}

// Reports whether an asset's exact bytes have already had this kind of
// enrichment run -- the content-hash cache check that lets the enqueue path skip
// unchanged media (returns 1 when a matching run exists, else 0).
func (q *Queries) HasEnrichmentRun(ctx context.Context, arg HasEnrichmentRunParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasEnrichmentRun, arg.AssetID, arg.Kind, arg.ContentHash)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const insertFace = `-- name: InsertFace :exec
INSERT INTO faces (
    id, asset_id, person_id, bbox_x, bbox_y, bbox_w, bbox_h,
    confidence, ext_ref, content_hash, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
`

type InsertFaceParams struct {
	ID          string  `json:"id"`
	AssetID     string  `json:"asset_id"`
	PersonID    *string `json:"person_id"`
	BboxX       float64 `json:"bbox_x"`
	BboxY       float64 `json:"bbox_y"`
	BboxW       float64 `json:"bbox_w"`
	BboxH       float64 `json:"bbox_h"`
	Confidence  float64 `json:"confidence"`
	ExtRef      string  `json:"ext_ref"`
	ContentHash string  `json:"content_hash"`
}

func (q *Queries) InsertFace(ctx context.Context, arg InsertFaceParams) error {
	_, err := q.db.ExecContext(ctx, insertFace,
		arg.ID,
		arg.AssetID,
		arg.PersonID,
		arg.BboxX,
		arg.BboxY,
		arg.BboxW,
		arg.BboxH,
		arg.Confidence,
		arg.ExtRef,
		arg.ContentHash,
	)
	return err
}

const listAssetIDsForPerson = `-- name: ListAssetIDsForPerson :many
SELECT DISTINCT f.asset_id
FROM faces f
JOIN assets a ON a.id = f.asset_id
WHERE f.person_id = ?
ORDER BY a.captured_at DESC, f.asset_id ASC
`

// Distinct asset ids that contain a face assigned to this person, for the
// "all photos of X" People view, newest captures first then stable by id.
func (q *Queries) ListAssetIDsForPerson(ctx context.Context, personID *string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAssetIDsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacesForAsset = `-- name: ListFacesForAsset :many
SELECT id, asset_id, person_id, bbox_x, bbox_y, bbox_w, bbox_h,
       confidence, ext_ref, content_hash
FROM faces WHERE asset_id = ?
ORDER BY id ASC
`

type ListFacesForAssetRow struct {
	ID          string  `json:"id"`
	AssetID     string  `json:"asset_id"`
	PersonID    *string `json:"person_id"`
	BboxX       float64 `json:"bbox_x"`
	BboxY       float64 `json:"bbox_y"`
	BboxW       float64 `json:"bbox_w"`
	BboxH       float64 `json:"bbox_h"`
	Confidence  float64 `json:"confidence"`
	ExtRef      string  `json:"ext_ref"`
	ContentHash string  `json:"content_hash"`
}

func (q *Queries) ListFacesForAsset(ctx context.Context, assetID string) ([]ListFacesForAssetRow, error) {
	rows, err := q.db.QueryContext(ctx, listFacesForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacesForAssetRow{}
	for rows.Next() {
		var i ListFacesForAssetRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.PersonID,
			&i.BboxX,
			&i.BboxY,
			&i.BboxW,
			&i.BboxH,
			&i.Confidence,
			&i.ExtRef,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacesForPerson = `-- name: ListFacesForPerson :many
SELECT id, asset_id, person_id, bbox_x, bbox_y, bbox_w, bbox_h,
       confidence, ext_ref, content_hash
FROM faces WHERE person_id = ?
ORDER BY id ASC
`

type ListFacesForPersonRow struct {
	ID          string  `json:"id"`
	AssetID     string  `json:"asset_id"`
	PersonID    *string `json:"person_id"`
	BboxX       float64 `json:"bbox_x"`
	BboxY       float64 `json:"bbox_y"`
	BboxW       float64 `json:"bbox_w"`
	BboxH       float64 `json:"bbox_h"`
	Confidence  float64 `json:"confidence"`
	ExtRef      string  `json:"ext_ref"`
	ContentHash string  `json:"content_hash"`
}

func (q *Queries) ListFacesForPerson(ctx context.Context, personID *string) ([]ListFacesForPersonRow, error) {
	rows, err := q.db.QueryContext(ctx, listFacesForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacesForPersonRow{}
	for rows.Next() {
		var i ListFacesForPersonRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.PersonID,
			&i.BboxX,
			&i.BboxY,
			&i.BboxW,
			&i.BboxH,
			&i.Confidence,
			&i.ExtRef,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonAssetCounts = `-- name: ListPersonAssetCounts :many
SELECT person_id, COUNT(DISTINCT asset_id) AS asset_count
FROM faces
WHERE person_id IS NOT NULL
GROUP BY person_id
`

type ListPersonAssetCountsRow struct {
	PersonID   *string `json:"person_id"`
	AssetCount int64   `json:"asset_count"`
}

// Per-person face/asset counts for the People view (how many photos each person
// appears in). Counts distinct assets, not raw faces.
func (q *Queries) ListPersonAssetCounts(ctx context.Context) ([]ListPersonAssetCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonAssetCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonAssetCountsRow{}
	for rows.Next() {
		var i ListPersonAssetCountsRow
		if err := rows.Scan(&i.PersonID, &i.AssetCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersons = `-- name: ListPersons :many
SELECT id, name, cover_face_id, ext_collection FROM persons
ORDER BY (name = '') ASC, name ASC, id ASC
`

type ListPersonsRow struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	CoverFaceID   string `json:"cover_face_id"`
	ExtCollection string `json:"ext_collection"`
}

// All persons, named clusters first (then unknown), each ordered by name/id, so
// the People view shows labelled people ahead of pending-unknown clusters.
func (q *Queries) ListPersons(ctx context.Context) ([]ListPersonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonsRow{}
	for rows.Next() {
		var i ListPersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoverFaceID,
			&i.ExtCollection,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const personForExtRef = `-- name: PersonForExtRef :one
SELECT person_id FROM faces
WHERE ext_ref = ? AND person_id IS NOT NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The person a previously-indexed face (identified by its backend ext_ref, e.g.
// a Rekognition FaceId) is assigned to. Returns the most recent assignment when
// a ref somehow appears more than once. Used by the pipeline to resolve a
// collection-search hit to one of our person clusters.
func (q *Queries) PersonForExtRef(ctx context.Context, extRef string) (*string, error) {
	row := q.db.QueryRowContext(ctx, personForExtRef, extRef)
	var person_id *string
	err := row.Scan(&person_id)
	return person_id, err
}

const recordEnrichmentRun = `-- name: RecordEnrichmentRun :exec
INSERT INTO enrichment_runs (asset_id, kind, content_hash, ran_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(asset_id, kind, content_hash) DO UPDATE SET
    ran_at = datetime('now')
`

type RecordEnrichmentRunParams struct {
	AssetID     string `json:"asset_id"`
	Kind        string `json:"kind"`
	ContentHash string `json:"content_hash"`
}

func (q *Queries) RecordEnrichmentRun(ctx context.Context, arg RecordEnrichmentRunParams) error {
	_, err := q.db.ExecContext(ctx, recordEnrichmentRun, arg.AssetID, arg.Kind, arg.ContentHash)
	return err
}

const renamePerson = `-- name: RenamePerson :execrows
UPDATE persons
SET name = ?, updated_at = datetime('now')
WHERE id = ?
`

type RenamePersonParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) RenamePerson(ctx context.Context, arg RenamePersonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renamePerson, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPersonCoverFace = `-- name: SetPersonCoverFace :exec
UPDATE persons
SET cover_face_id = ?, updated_at = datetime('now')
WHERE id = ?
`

type SetPersonCoverFaceParams struct {
	CoverFaceID string `json:"cover_face_id"`
	ID          string `json:"id"`
}

func (q *Queries) SetPersonCoverFace(ctx context.Context, arg SetPersonCoverFaceParams) error {
	_, err := q.db.ExecContext(ctx, setPersonCoverFace, arg.CoverFaceID, arg.ID)
	return err
}

const upsertPerson = `-- name: UpsertPerson :exec

INSERT INTO persons (id, name, cover_face_id, ext_collection, created_at, updated_at)
VALUES (?, ?, ?, ?, datetime('now'), datetime('now'))
ON CONFLICT(id) DO UPDATE SET
    name           = excluded.name,
    cover_face_id  = excluded.cover_face_id,
    ext_collection = excluded.ext_collection,
    updated_at     = datetime('now')
`

type UpsertPersonParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	CoverFaceID   string `json:"cover_face_id"`
	ExtCollection string `json:"ext_collection"`
}

// ai-people queries (sqlc). Domains: persons (named/unknown face clusters),
// faces (detected faces with bbox + external vector ref), and the enrichment
// run ledger (content-hash cache for enrich-ai / face-index). See migration
// 0400_people.sql for the schema and docs/specs/_contracts.md section 6 for
// conventions. KEEP THIS FILE PURE ASCII: sqlc v1.31 corrupts generated
// constants on any non-ASCII byte.
func (q *Queries) UpsertPerson(ctx context.Context, arg UpsertPersonParams) error {
	_, err := q.db.ExecContext(ctx, upsertPerson,
		arg.ID,
		arg.Name,
		arg.CoverFaceID,
		arg.ExtCollection,
	)
	return err
}
