// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package store

import (
	"context"
)

const getMeta = `-- name: GetMeta :one

SELECT value FROM app_meta WHERE key = ?
`

// Platform-owned queries over the app_meta key/value table.
func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setMeta = `-- name: SetMeta :exec
INSERT INTO app_meta (key, value, updated_at)
VALUES (?, ?, datetime('now'))
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetMeta(ctx context.Context, arg SetMetaParams) error {
	_, err := q.db.ExecContext(ctx, setMeta, arg.Key, arg.Value)
	return err
}
