// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	AssignFacePerson(ctx context.Context, arg AssignFacePersonParams) error
	// ClaimJob marks one selected row claimed, sets its lease and bumps attempts.
	// It is guarded by the same predicate as SelectClaimable so a row that changed
	// between select and update (impossible under the single writer, but correct
	// regardless) is not double-claimed.
	ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error)
	CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error)
	CountFacesForPerson(ctx context.Context, personID *string) (int64, error)
	CountFilesForAsset(ctx context.Context, assetID string) (int64, error)
	CountJobsByStatus(ctx context.Context, status string) (int64, error)
	DeleteAsset(ctx context.Context, id string) error
	DeleteDerivativesForAsset(ctx context.Context, assetID string) error
	DeleteEmbedding(ctx context.Context, assetID string) error
	DeleteFacesForAsset(ctx context.Context, assetID string) error
	DeleteFile(ctx context.Context, mediaPath string) error
	DeleteMetadata(ctx context.Context, assetID string) error
	DeletePerson(ctx context.Context, id string) error
	// jobs-worker queries over the durable job queue (see migration 0300_jobs.sql).
	// The claim path is split into a SELECT of claimable ids and a per-id UPDATE so
	// it can run inside one serialized write transaction; with the single-writer
	// SQLite connection this guarantees no two claims ever take the same row.
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	FailJob(ctx context.Context, arg FailJobParams) (int64, error)
	GetAsset(ctx context.Context, id string) (Asset, error)
	GetDerivative(ctx context.Context, arg GetDerivativeParams) (Derivative, error)
	GetEmbedding(ctx context.Context, assetID string) (GetEmbeddingRow, error)
	GetFace(ctx context.Context, id string) (GetFaceRow, error)
	GetFile(ctx context.Context, mediaPath string) (File, error)
	GetJob(ctx context.Context, id string) (Job, error)
	// Platform-owned queries over the app_meta key/value table.
	GetMeta(ctx context.Context, key string) (string, error)
	GetMetadata(ctx context.Context, assetID string) (Metadata, error)
	GetPerson(ctx context.Context, id string) (GetPersonRow, error)
	// Reports whether an asset's exact bytes have already had this kind of
	// enrichment run -- the content-hash cache check that lets the enqueue path skip
	// unchanged media (returns 1 when a matching run exists, else 0).
	HasEnrichmentRun(ctx context.Context, arg HasEnrichmentRunParams) (bool, error)
	InsertFace(ctx context.Context, arg InsertFaceParams) error
	// All assets in a library (for warm-cache / bulk passes), folder order.
	ListAllAssets(ctx context.Context, alias string) ([]Asset, error)
	// Full snapshot of catalogued files for a library, used by the reconcile scan
	// to diff against the on-disk walk on (path, mtime, size).
	ListAllFiles(ctx context.Context, alias string) ([]File, error)
	// Distinct asset ids that contain a face assigned to this person, for the
	// "all photos of X" People view, newest captures first then stable by id.
	ListAssetIDsForPerson(ctx context.Context, personID *string) ([]string, error)
	// Keyset (cursor) pagination by base_name within a folder. The cursor is the
	// last base_name seen; pass "" to start. Fetches limit+1 so the caller can
	// detect a next page.
	ListAssetsByDir(ctx context.Context, arg ListAssetsByDirParams) ([]Asset, error)
	// Distinct non-empty camera models in a library, for the camera facet listing.
	ListCameras(ctx context.Context, alias string) ([]string, error)
	ListDerivativesForAsset(ctx context.Context, assetID string) ([]Derivative, error)
	// All distinct (non-empty) directories holding assets in a library. The browse
	// handler derives immediate child folders of a given dir from this in Go (the
	// substring arithmetic SQLite would need is brittle through sqlc's parser).
	ListDirsForLibrary(ctx context.Context, alias string) ([]string, error)
	// All embeddings (asset_id + vector) for the brute-force cosine search. At
	// personal-library scale this full scan is cheap; if it ever isn't, this is the
	// single query to replace with an ANN index.
	ListEmbeddings(ctx context.Context) ([]ListEmbeddingsRow, error)
	ListFacesForAsset(ctx context.Context, assetID string) ([]ListFacesForAssetRow, error)
	ListFacesForPerson(ctx context.Context, personID *string) ([]ListFacesForPersonRow, error)
	ListFilesForAsset(ctx context.Context, assetID string) ([]File, error)
	// Per-person face/asset counts for the People view (how many photos each person
	// appears in). Counts distinct assets, not raw faces.
	ListPersonAssetCounts(ctx context.Context) ([]ListPersonAssetCountsRow, error)
	// All persons, named clusters first (then unknown), each ordered by name/id, so
	// the People view shows labelled people ahead of pending-unknown clusters.
	ListPersons(ctx context.Context) ([]ListPersonsRow, error)
	// The person a previously-indexed face (identified by its backend ext_ref, e.g.
	// a Rekognition FaceId) is assigned to. Returns the most recent assignment when
	// a ref somehow appears more than once. Used by the pipeline to resolve a
	// collection-search hit to one of our person clusters.
	PersonForExtRef(ctx context.Context, extRef string) (*string, error)
	RecordEnrichmentRun(ctx context.Context, arg RecordEnrichmentRunParams) error
	RenamePerson(ctx context.Context, arg RenamePersonParams) (int64, error)
	// RetryJob reschedules a failed-but-retryable job: back to pending with a
	// future availability (caller computes the backoff offset string).
	RetryJob(ctx context.Context, arg RetryJobParams) (int64, error)
	// SelectClaimable returns up to ? ids of jobs that are claimable right now: a
	// pending job whose availability has arrived, or a claimed job whose lease has
	// lapsed (worker died/stalled). Oldest-available first for FIFO fairness.
	SelectClaimable(ctx context.Context, limit int64) ([]string, error)
	SetAssetCapturedAt(ctx context.Context, arg SetAssetCapturedAtParams) error
	SetMeta(ctx context.Context, arg SetMetaParams) error
	SetPersonCoverFace(ctx context.Context, arg SetPersonCoverFaceParams) error
	// media-pipeline catalog queries (sqlc). Domain: assets / files / derivatives.
	// See docs/specs/_contracts.md sec.3 for the type shapes and sec.6 for conventions.
	UpsertAsset(ctx context.Context, arg UpsertAssetParams) error
	UpsertDerivative(ctx context.Context, arg UpsertDerivativeParams) error
	UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error
	UpsertFile(ctx context.Context, arg UpsertFileParams) error
	// search-index queries (sqlc). Domains: metadata (normalized EXIF/ffprobe
	// facts), the assets_fts full-text index, and the semantic-search embeddings.
	// See migration 0200_metadata_search.sql for the schema and
	// docs/specs/_contracts.md sec.6 for conventions. KEEP THIS FILE PURE ASCII:
	// sqlc v1.31 corrupts generated constants on any non-ASCII byte.
	UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) error
	// ai-people queries (sqlc). Domains: persons (named/unknown face clusters),
	// faces (detected faces with bbox + external vector ref), and the enrichment
	// run ledger (content-hash cache for enrich-ai / face-index). See migration
	// 0400_people.sql for the schema and docs/specs/_contracts.md section 6 for
	// conventions. KEEP THIS FILE PURE ASCII: sqlc v1.31 corrupts generated
	// constants on any non-ASCII byte.
	UpsertPerson(ctx context.Context, arg UpsertPersonParams) error
}

var _ Querier = (*Queries)(nil)
