// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"
)

const deleteEmbedding = `-- name: DeleteEmbedding :exec
DELETE FROM embeddings WHERE asset_id = ?
`

func (q *Queries) DeleteEmbedding(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteEmbedding, assetID)
	return err
}

const deleteMetadata = `-- name: DeleteMetadata :exec
DELETE FROM metadata WHERE asset_id = ?
`

func (q *Queries) DeleteMetadata(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteMetadata, assetID)
	return err
}

const getEmbedding = `-- name: GetEmbedding :one
SELECT asset_id, dim, vec FROM embeddings WHERE asset_id = ?
`

type GetEmbeddingRow struct {
	AssetID string `json:"asset_id"`
	Dim     int64  `json:"dim"`
	Vec     []byte `json:"vec"`
}

func (q *Queries) GetEmbedding(ctx context.Context, assetID string) (GetEmbeddingRow, error) {
	row := q.db.QueryRowContext(ctx, getEmbedding, assetID)
	var i GetEmbeddingRow
	err := row.Scan(&i.AssetID, &i.Dim, &i.Vec)
	return i, err
}

const getMetadata = `-- name: GetMetadata :one
SELECT asset_id, captured_at, camera_make, camera_model, lens,
       width, height, orientation, duration_ms, codec, gps_lat, gps_lng,
       source, indexed_at
FROM metadata WHERE asset_id = ?
`

func (q *Queries) GetMetadata(ctx context.Context, assetID string) (Metadata, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, assetID)
	var i Metadata
	err := row.Scan(
		&i.AssetID,
		&i.CapturedAt,
		&i.CameraMake,
		&i.CameraModel,
		&i.Lens,
		&i.Width,
		&i.Height,
		&i.Orientation,
		&i.DurationMs,
		&i.Codec,
		&i.GpsLat,
		&i.GpsLng,
		&i.Source,
		&i.IndexedAt,
	)
	return i, err
}

const listCameras = `-- name: ListCameras :many
SELECT DISTINCT m.camera_model
FROM metadata m
JOIN assets a ON a.id = m.asset_id
WHERE a.alias = ? AND m.camera_model <> ''
ORDER BY m.camera_model
`

// Distinct non-empty camera models in a library, for the camera facet listing.
func (q *Queries) ListCameras(ctx context.Context, alias string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCameras, alias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var camera_model string
		if err := rows.Scan(&camera_model); err != nil {
			return nil, err
		}
		items = append(items, camera_model)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddings = `-- name: ListEmbeddings :many
SELECT asset_id, dim, vec FROM embeddings
`

type ListEmbeddingsRow struct {
	AssetID string `json:"asset_id"`
	Dim     int64  `json:"dim"`
	Vec     []byte `json:"vec"`
}

// All embeddings (asset_id + vector) for the brute-force cosine search. At
// personal-library scale this full scan is cheap; if it ever isn't, this is the
// single query to replace with an ANN index.
func (q *Queries) ListEmbeddings(ctx context.Context) ([]ListEmbeddingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbeddingsRow{}
	for rows.Next() {
		var i ListEmbeddingsRow
		if err := rows.Scan(&i.AssetID, &i.Dim, &i.Vec); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO embeddings (asset_id, dim, vec, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(asset_id) DO UPDATE SET
    dim        = excluded.dim,
    vec        = excluded.vec,
    updated_at = datetime('now')
`

type UpsertEmbeddingParams struct {
	AssetID string `json:"asset_id"`
	Dim     int64  `json:"dim"`
	Vec     []byte `json:"vec"`
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmbedding, arg.AssetID, arg.Dim, arg.Vec)
	return err
}

const upsertMetadata = `-- name: UpsertMetadata :exec

INSERT INTO metadata (
    asset_id, captured_at, camera_make, camera_model, lens,
    width, height, orientation, duration_ms, codec, gps_lat, gps_lng, source,
    indexed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(asset_id) DO UPDATE SET
    captured_at  = excluded.captured_at,
    camera_make  = excluded.camera_make,
    camera_model = excluded.camera_model,
    lens         = excluded.lens,
    width        = excluded.width,
    height       = excluded.height,
    orientation  = excluded.orientation,
    duration_ms  = excluded.duration_ms,
    codec        = excluded.codec,
    gps_lat      = excluded.gps_lat,
    gps_lng      = excluded.gps_lng,
    source       = excluded.source,
    indexed_at   = datetime('now')
`

type UpsertMetadataParams struct {
	AssetID     string   `json:"asset_id"`
	CapturedAt  *string  `json:"captured_at"`
	CameraMake  string   `json:"camera_make"`
	CameraModel string   `json:"camera_model"`
	Lens        string   `json:"lens"`
	Width       int64    `json:"width"`
	Height      int64    `json:"height"`
	Orientation int64    `json:"orientation"`
	DurationMs  int64    `json:"duration_ms"`
	Codec       string   `json:"codec"`
	GpsLat      *float64 `json:"gps_lat"`
	GpsLng      *float64 `json:"gps_lng"`
	Source      string   `json:"source"`
}

// search-index queries (sqlc). Domains: metadata (normalized EXIF/ffprobe
// facts), the assets_fts full-text index, and the semantic-search embeddings.
// See migration 0200_metadata_search.sql for the schema and
// docs/specs/_contracts.md sec.6 for conventions. KEEP THIS FILE PURE ASCII:
// sqlc v1.31 corrupts generated constants on any non-ASCII byte.
func (q *Queries) UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetadata,
		arg.AssetID,
		arg.CapturedAt,
		arg.CameraMake,
		arg.CameraModel,
		arg.Lens,
		arg.Width,
		arg.Height,
		arg.Orientation,
		arg.DurationMs,
		arg.Codec,
		arg.GpsLat,
		arg.GpsLng,
		arg.Source,
	)
	return err
}
