name: fs-image-manager CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14.15'
        check-latest: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.3'
    - name: Run Test & Build
      run: make dep-tools deps test build
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-webapp
        path: |
          dist/fs-image-manager-*.tar.bz2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-node-docker-img:$(git rev-parse --short "$GITHUB_SHA")
