name: fs-image-manager Container CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      uses: docker/login-action@v1
      name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      uses: docker/build-push-action@v2
      name: Build and push
      id: docker_build
      with:
        push: true
        tags: imyousuf/go-node-docker-img:${{ env.GITHUB_SHA }}
